### ISSUE TITLE
Can't complete NZBGeek config due to SSL handshake failure

### ISSUE THREAD

**Issue by clandestinecephalopod** [theotherp/nzbhydra2#504]
Just noticed that geek was disabled by system. When trying to check capabilities it says the following:

> The config of this indexer is incomplete. Please click the button at the bottom to check its capabilities and complete its configuration.

> Error testing capabilities - An error occurred while contacting the indexer. It will not be usable until the caps check has been executed. You can trigger it manually from the indexer config box

"nzbgeek.info" was already in Disable SNI. I read elsewhere this solved the issue for some. 
I'm using Hydra2 in Chrome on Win10.
Slug, dog, etc. are all working fine.

Let me know if you need anything else.

log: 
[nzbhydra-debuginfos-2020-02-16-17-02.zip](https://github.com/theotherp/nzbhydra2/files/4210198/nzbhydra-debuginfos-2020-02-16-17-02.zip)

**Comment by theotherp** [comment]
Hm, I had expected all SSL related errors to go away with some changes I made a couple of weeks ago... :-(

Please do the following:

Please do the following:
1. In the main config enable the logging marker "HTTPS" and set the log file level to debug
2. Restart Hydra
3. Execute the caps check for nzbgeek
4. Create the debug infos zip and post them here again
5. Disable the logging marker again and restart Hydra (otherwise it will write a huuuge file in the logs folder).

**Comment by clandestinecephalopod** [comment]
[nzbhydra-debuginfos-2020-02-16-21-28.zip](https://github.com/theotherp/nzbhydra2/files/4210865/nzbhydra-debuginfos-2020-02-16-21-28.zip)

**Comment by theotherp** [comment]
Hm, that's weird. There's a file missing / empty. Could you please check the logs folder for a file `system.err.log` and see if it has any content?

**Comment by theotherp** [comment]
Or you could just add `api.nzbgeek.info` to the lists of hosts for which to disable SSL verification.

**Comment by clandestinecephalopod** [comment]
`system.err.log` file is present but indeed empty (0 KB).

I disabled SSL verification for geek and tried adding it again from scratch:
> Connection check failed - The connection to the indexer failed: Error while communicating with indexer NZBGeek. Server returned: javax.net.ssl.SSLHandshakeException: Received fatal alert: handshake_failure

:-(

**Comment by theotherp** [comment]
Try adding `*.nzbgek.info` and/or `*nzbgeek.info` and/or `nzbgeek.info`. I can't check what's correct right now.

**Comment by clandestinecephalopod** [comment]
Tried adding them all. No change unfortunately.

**Comment by agrudsky** [comment]
I am also having the same issue with Hydra on Windows 10. Tried disabling verification for the hosts as above but this didn't fix it either. Debug ZIP is attached. Thanks for any help in advance.

[nzbhydra-debuginfos-2020-02-17-13-45.zip](https://github.com/theotherp/nzbhydra2/files/4215623/nzbhydra-debuginfos-2020-02-17-13-45.zip)

**Comment by theotherp** [comment]
Thanks for the debug infos. 

@agrudsky Could you please update to a newer java installation. See https://adoptopenjdk.net/ If that doesn't work see below.

@clandestinecephalopod 
I just released a new version. Please update and repeat the steps.

I can't explain why it wouldn't work for you, I have Windows 10 as well and the SSL certificates should be loaded from the same source.

Sorry for the inconvenience.

**Comment by agrudsky** [comment]
Thank you for your prompt reply! I updated Java and Hydra, tried again, still the same thing. Debug attached.

[nzbhydra-debuginfos-2020-02-17-16-45.zip](https://github.com/theotherp/nzbhydra2/files/4216355/nzbhydra-debuginfos-2020-02-17-16-45.zip)

**Comment by theotherp** [comment]
Yeah, that was just to get more debug infos. I'll take a look tomorrow.

**Comment by clandestinecephalopod** [comment]
> Sorry for the inconvenience.

Minor inconvenience! You're doing great. Hydra has been absolutely amazing overall.

Although, with that said: Updated. Repeated. No change.
[nzbhydra-debuginfos-2020-02-19-00-33.zip](https://github.com/theotherp/nzbhydra2/files/4222283/nzbhydra-debuginfos-2020-02-19-00-33.zip)

**Comment by theotherp** [comment]
I have no idea what's going on. I downloaded the java versions you use and ran Hydra using them and I could connect fine to nzbgeek. Adding a host with an unknown certificate to the ignore list worked as well.

For some reason your instances don't allow some SSL cipher suites, meaning they can't connect to nzbgeek using the SSL protocols that nzbgeek allows.

Please do this:

1.  Download [Ciphers.zip](https://github.com/theotherp/nzbhydra2/files/4241048/Ciphers.zip).
2. Extract it anywhere.
3. Open a command prompt and go to the directory.
4. Run `java Ciphers`.
5. Post the output. That will tell me what SSL ciphers your java installation supports.

The last step trying to reproduce this would be to run your instances using your installations.

So please zip your java installation and your complete hydra folder (this will contain your API keys and so on but I promise I won't use them, I have enough of my own), upload the zip somewhere and send me the link to theotherp@gmx.de. If you're not willing to do that I'm out of ideas.

@agrudsky Your java installation is located here: C:\Program Files\AdoptOpenJDK\jdk-11.0.6.10-hotspot

@clandestinecephalopod Your java installation is located here: C:\Program Files\Java\jre1.8.0_241

**Comment by agrudsky** [comment]
Thanks again for your attention and help with this -- you certainly don't have to go this far and I (along with @clandestinecephalopod, I'm sure) really appreciate it. I sent over a ZIP of my installation as you asked. 

Ciphers here: https://pastebin.com/u6DQ120b

**Comment by jant90** [comment]
I believe I have the same issue since late december when NZBGeek disabled anything lower than TLS 1.2, I haven't been able to use Geek through Hydra ever since.

I've been running OpenJDK JRE 8 on my Manjaro (Arch based) system and it always worked great for Hydra, apart from recent NZBGeek SSL issues. This got me wondering though: @theotherp **what is the recommended JRE version for Hydra?**

Anyways, I decided to install OpenJDK JRE's 8, 10, 11, 13 and Oracle JRE's 8, 10, 13 and run the NZBGeek capabilities check with Hydra with all of them. All versions seemed to run Hydra fine but all failed the Geek capabilities check.

I also tried running Ciphers with al JRE versions, but only versions 11 and 13 can run the class, older versions return an error. OpenJDK JRE 13 and Oracle JRE 13 return the exact same ciphers:
OpenJDK JRE 11 ciphers: https://pastebin.com/b5Yc7Zwp
OpenJDK/Oracle JRE 13 ciphers: https://pastebin.com/V4dMPaA8

**Comment by theotherp** [comment]
@jant90 I've run Hydra with the same JDK/JRE versions as the others and it works fine for me. I can't really explain it. There should be no difference in the ciphers between their installations (and yours) and mine. That's why I asked for the complete package to find out if there's any difference I can find.

I've tested it locally with AdaptOpenJDK 8 and 11 and with Oracle Java 8 and 11 and all were able to connect to nzbgeek just fine.

**Comment by jant90** [comment]
No worries @theotherp, I was just trying to give some information hoping it would help you :). Do you have a recommended (or preferred) JRE version for Hydra?

And what ciphers are we looking for if we want to do a successful handshake with Geek? I want to run `java Ciphers` on a few other systems and check what is returned.

**Comment by jant90** [comment]
I resolved the issue for me. Hope this helps others as well:
1. Download the [latest release of NZBHydra 2 from GitHub](https://github.com/theotherp/nzbhydra2/releases/latest).
2. Take the NZBHydra 2 binary (`nzbhydra2` for Linux) from the zip file and overwrite the one on your system.
3. Restart NZBHydra 2.

Note that I was already running v2.14.1 so I guess the auto-updater failed (probably a while ago). I noticed that my local binary was from 2019-02-09 while the one from GitHub is from 2019-04-04. All other files were equal and thus updated properly by the auto-updater.

**Comment by theotherp** [comment]
@jant90 That makes sense because at some point the wrapper used a parameter to start java which caused some ciphers to be disabled. Thanks for the test, I probably would've needed some time until I had gotten to that conclusion.

But I implemented a mechanism which should've informed you about the wrapper files being outdated. I'll need to find out why that didn't work. Again, thanks a lot for debugging this.

@agrudsky @clandestinecephalopod Please update your exe files from the latest release. It should work then.

**Comment by theotherp** [comment]
@agrudsky It looks like you were warned that the wrapper was outdated (at some point, at least that's what the database says). Do you remember that warning and ignoring it?

**Comment by clandestinecephalopod** [comment]
Well whaddaya know, that solved it. @theotherp @jant90 thanks guys, you're the best!
To be honest, I don't really understand the solution, but I'm glad it works again :-)

**Comment by theotherp** [comment]
@clandestinecephalopod 

The wrapper exe calls java using a certain set of parameters. One of these parameters disables a set of SSL security features which prevents Java from establishing a secure connection with nzbgeek. The older version of the wrapper did set this parameter, the newer version of the wrapper (which has been out for quite a long time) does not. Because I don't run Hydra using that wrapper and never thought of that old version I never considered this to be the culprit. 

Now that I know what was the cause it makes sense: We had the same java code, we had the same java installation, the wrapper (which connects the two) was where your hydra instance and mine differed.

Is it possible that at some point you got a warning that the wrapper was outdated and you clicked it away? I tested it locally and hydra should warn you about that.

**Comment by clandestinecephalopod** [comment]
Thanks for the the explanation. As for the warning, I can't say that I remember ever seeing it, but it's indeed very possible I clicked it away. I do sometimes dismiss pop-ups too quickly or unknowingly mis-click, later hoping that it either wasn't important or that it would show up again.

What does the dialog ask me to do about the outdated wrappers? Is it an auto or manual operation?

**Comment by theotherp** [comment]
The popup tells you to manually update the wrapper and explains how to do so. I've adding output to the debug infos to warn me when somebody uses outdated wrappers.

I'll consider this fixed and close the issue.

**Comment by agrudsky** [comment]
Yes, working for me too! Thank you @theotherp and @jant90 for the help. 

As for the popup -- I do not recall seeing it but it is entirely possible that I did and just clicked it away. Would it have presented itself multiple times or just once?
