### ISSUE TITLE
BUG cannot add indexer by reading Jackett config 

### ISSUE THREAD

**Issue by tigermanIT** [theotherp/nzbhydra2#832]
[nzbhydra-debuginfos-2023-01-27-22-13.zip](https://github.com/theotherp/nzbhydra2/files/10523208/nzbhydra-debuginfos-2023-01-27-22-13.zip)

Hi, cannot add indexer by reading Jackett config version v0.20.2721

Steps to reproduce : 

Starting nzbhydra2 Version: 5.1.1
Go to http://localhost:5076/config/indexers
Add new indexer
Torrents - Choose from presets - Read from jackett config 

Jackett config : 
Host : http://127.0.0.1:9117
API KEY : aqvj6yk7p.....

get this when I click submit  :
An error occurred:
undefined

Message: undefined

Please can you help 
Giuseppe

**Comment by theotherp** [comment]
Sorry for the troubles. Please create and attach a debug infos zip.

**Comment by tigermanIT** [comment]
debug infos was already attached in my previous message

I'm attaching it again

thanks for your support

[nzbhydra-debuginfos-2023-01-27-22-13 (1).zip](https://github.com/theotherp/nzbhydra2/files/10527313/nzbhydra-debuginfos-2023-01-27-22-13.1.zip)

**Comment by theotherp** [comment]
Sorry, I opened a bunch of tabs and posted that everywhere...

**Comment by theotherp** [comment]
Probably fixed in the next release. I wasn't able to reproduce the source of the issue but hopefully how it affects saving the config.

**Comment by tigermanIT** [comment]
Hello
updated to 5.1.2
but issue still exists

also if I try to create a debug infos zip I get this error message :  
An error occurred:
undefined
Message: undefined

so I can attach nzbhydra2.log : 
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/10660563/nzbhydra2.log)

**Comment by theotherp** [comment]
The debug infos can be created but not uploaded, it seems. But the log is enough.

**Comment by theotherp** [comment]
Call http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab?apikey=<apikey>&t=indexers&configured=true (with your jackett api key) in your browser and check the output. Does it return indexer information? Or do you get an error?

In any case, please remove all API keys for private indexers and post the response.

**Comment by tigermanIT** [comment]
> Call http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab?apikey=&t=indexers&configured=true (with your jackett api key) in your browser and check the output. Does it return indexer information? Or do you get an error?

If I call in my browser then it returns indexer information immediately, no error

but if I go to http://localhost:5076/config/indexers
add indexer -- Torrents choose from presets -- Jackett/Cardigann
and set 
Host : http://127.0.0.1:9117/api/v2.0/indexers/all/results/torznab
API Key : my Jackett api key
then I get this error message 
The connection to the indexer failed: Error while communicating with indexer Jackett/Cardigann. Server returned: org.nzbhydra.webaccess.WebAccessException: Read timed out

> 
> In any case, please remove all API keys for private indexers and post the response.
Please explain me how I can do it

**Comment by theotherp** [comment]
Please post the output. NZBHydra cannot parse it for some reason while it can in my case so I think there's something in the XML that causes it but I can't fix it without the output.

**Comment by tigermanIT** [comment]
attached file with output
[index.pdf](https://github.com/theotherp/nzbhydra2/files/10661804/index.pdf)

**Comment by theotherp** [comment]
I don't understand what's going on. NZBHydra can parse that just fine. I even configured all your trackers in my jackett (which was a pain because holy shit you do have many) and I can parse it. I have modified the code to hopefully show a better error message.

**Comment by theotherp** [comment]
Please try with the new version and then post new debug infos.

**Comment by tigermanIT** [comment]
I see two problems here

First :  
Start nzbhydra2 Version: 5.1.4
Go to http://localhost:5076/config/indexers
Add new indexer
Torrents - Choose from presets - Read from jackett config
I get this error message : 
Error reading jackett config
HTTP Status 500 – Internal Server Error

but If I call in my browser then it returns indexer information immediately, no error : 
http://[127.0.0.1:9117/api/v2.0/indexers/all/results/torznab?apikey=&t=indexers&configured=true]

Second,
when I create debug infos then I get :  
HTTP Status 500 – Internal Server Error

So what's going on ! I always get 
HTTP Status 500 – Internal Server Error

attached log file :
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/10697932/nzbhydra2.log)

**Comment by theotherp** [comment]
Yeah I forgot to fix the upload infos stuff but it should work if you create and download them instead of upload them.

Unfortunately I don't get any more infos on why the "unmarsheling" failed. I thought it was the parsing but it must be something else. No idea what, though.

**Comment by theotherp** [comment]
Ok, I can finally reproduce.

**Comment by theotherp** [comment]
Pleae replace the core.exe in your folder with this one and test again: https://ufile.io/6h1yfja1

**Comment by tigermanIT** [comment]
yeah it works ! I can import indexers from Jackett
but still have problem with "Create and download debug infos"
still getting "HTTP Status 500 – Internal Server Error"

**Comment by theotherp** [comment]
Ok, post new log, then I can fix that too.

**Comment by tigermanIT** [comment]
[nzbhydra2.log](https://github.com/theotherp/nzbhydra2/files/10699799/nzbhydra2.log)

**Comment by theotherp** [comment]
I think you clicked "Create and upload debug infos"

**Comment by tigermanIT** [comment]
oh sorry you are right man
