### ISSUE TITLE
BUG NZB Finder does not provide any results for specific searches although it does for general searches

### ISSUE THREAD

**Issue by RDHoworth** [theotherp/nzbhydra2#872]
I have been using NZBHydra for many years, but am now having issues with NZB Finder. When I use the search facility in its simplest form, i.e. just search without specifying any criteria, then NZB finder seems to work fine and returns many results, although it does not show any images at all. The search also works if I search for a specific item with the check bos set to search using the IMDB ID. However, if I try to search for any specific item (by typing something into the search field) then NZB Finder returns 0 items. 

I also use NZB Planet and NZB Geek, and both of these work well.

I hafe tried to remove the NZB Finder indexer, and reapplied it and also change the API key, but it still fails.

I have uploaded the NZBHydra logs top https://file.io/WfG7roeuvPvk and included three screenshots
<img width="784" alt="Screen Shot 2023-06-24 at 06 16 09 am" src="https://github.com/theotherp/nzbhydra2/assets/44145101/de4b6a89-cd5f-4ba4-b676-fee1d6010485">
<img width="780" alt="Screen Shot 2023-06-24 at 06 15 43 am" src="https://github.com/theotherp/nzbhydra2/assets/44145101/711a066a-257a-447b-8472-994b14908146">
<img width="851" alt="Screen Shot 2023-06-24 at 06 14 23 am" src="https://github.com/theotherp/nzbhydra2/assets/44145101/6cf1de23-8027-4815-b2ad-4e2f797a3c4d">

**Comment by theotherp** [comment]
I'm currently on vacation but I'll take a look next week.

**Comment by theotherp** [comment]
You set the logging level to "ERROR" so the log barely contains any entries. There's really no good reason to do that, especially for the log file.

Please set the log file to DEBUG for the log file, reproduce the error and post new debug infos.

**Comment by RDHoworth** [comment]
Hi, I havve now set the logging level to DEBUG. I reran the and exported the logs.
[nzbhydra-debuginfos-2023-07-02-18-13.zip](https://github.com/theotherp/nzbhydra2/files/11930170/nzbhydra-debuginfos-2023-07-02-18-13.zip)

**Comment by theotherp** [comment]
I can't reproduce the problem and I can't find your example in the log. I can only see the search without any ID or query which returned results, no search for the word without using the ID.

So please repeat the search as shown in your second screenshot and create new debug infos.

By the way, in most cases it's better to search by ID, i.e. by using the autocomplete function.

**Comment by RDHoworth** [comment]
I am very sorry that I missed deselecting the criteria. I have redone this and l
attached the logs. This time, NZBFinder definitely returns 0 results
[nzbhydra-debuginfos-2023-07-02-19-42.zip](https://github.com/theotherp/nzbhydra2/files/11931133/nzbhydra-debuginfos-2023-07-02-19-42.zip)

**Comment by theotherp** [comment]
I see. It's because of the list of forbidden words you defined is used and NZB Finder doesn't seem to like the way I format it. I can fix that.

**Comment by RDHoworth** [comment]
That's great. Please let me know if I can help testing.

Thanks, Richard

**Comment by theotherp** [comment]
Fixed in next release.

**Comment by theotherp** [comment]
I'm waiting on feedback for another bug. If I haven't released by thursday please remind me ;-)

**Comment by RDHoworth** [comment]
Hi, unfortunately, he recent  release does not fix this issue at all.  I have attached a recent log. In addition, NZB Finder also still does 
[nzbhydra-debuginfos-2023-07-04-19-15.zip](https://github.com/theotherp/nzbhydra2/files/11951727/nzbhydra-debuginfos-2023-07-04-19-15.zip)
not display any images

**Comment by theotherp** [comment]
Sorry, you need to recheck the caps, I think.

**Comment by theotherp** [comment]
Searching for "transformers" works. Don't ask me why.

**Comment by theotherp** [comment]
The missing covers are their "fault", the results return `   <newznab:attr name="coverurl" value="https://nzbfinder.ws/covers/movies/no-cover.jpg"/>` which is a bit weird. I could filter that out but I'd rather they don't return the attribute if it there isn't a cover at all.

**Comment by RDHoworth** [comment]
I have rechecked the caps, and it did not make a diffeence. Howevver, I have noticed a little more. If I search for “transformer”, NZBFinder returns 0 results, but if I search for “transformers” it returns some results. 
Still no images returned
[nzbhydra-debuginfos-2023-07-04-20-34.zip](https://github.com/theotherp/nzbhydra2/files/11952000/nzbhydra-debuginfos-2023-07-04-20-34.zip)

[nzbhydra-debuginfos-2023-07-04-20-34.zip](https://github.com/theotherp/nzbhydra2/files/11951996/nzbhydra-debuginfos-2023-07-04-20-34.zip)
 no images returned

**Comment by theotherp** [comment]
See my last comment.
